/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zero_mp_MainActivity */

#ifndef _Included_com_zero_mp_MainActivity
#define _Included_com_zero_mp_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zero_mp_MainActivity
 * Method:    startMoniter
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zero_mp_MainActivity_startMoniter
  (JNIEnv *, jobject);

/*
 * Class:     com_zero_mp_MainActivity
 * Method:    stopMoniter
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zero_mp_MainActivity_stopMoniter
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
